version: '3.7'
services:
  postgresql:
    image: postgres:13-alpine
    ports:
      - '9999:9999'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef